version: "3"
services:
  # MongoDB container
  database:
    image: "mongo:latest"
    container_name: "mongo-db-database"
    environment:
      - MONGO_INITDB_DATABASE=mongo-test-db
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017-27019:27017-27019"
    volumes:
      - ./data/mongo-db-volume:/data/db
    restart: always
 app:
        build: .
        depends_on:
          - mongo-db-database
        environment:
          DATABASE_URL: db DATABASE_URL
          NODE_ENV: development
          PORT: 3000
        ports:
          - "3000:3000"
        command: npm run dev
        volumes:
          - .:/app/
          - /app/node_modules